### ISSUE TITLE
which version of nodejs can build this project

### ISSUE THREAD

**Issue by cgafeng** [BitShares/BitShares-JS#49]
**On Mac:**
  use node-v0.12.0 to install fail, can't build the bignum module.
  use node-v0.10.36 to install success, and success to run "npm test" and "npm run-script package_tests"

**On windows:**
  use node-v0.12.0 to install fail, can't build the bignum module.
  use node-v0.10.36 to install success, run "npm test" fail.
  "npm run-script package_tests" fail too, the error is:
```
    Error: Cannot find module 'd:\code\BitShares-JS\test\*.coffee' from 'd:\code\BitShares-JS'
```
  and after list all the .coffee file the tests build and run on browser success.
```
    "package_tests": "browserify test/wallet_test.coffee test/proof_of_work.coffee test/mail_transaction.coffee test/mail_test.coffee test/key_formats.coffee test/CryptoFunctions.coffee --debug --transform coffeeify --extension=.coffee >bitshares-mocha.js",
```

**Comment by cgafeng** [comment]
The error after run "npm test" on windows:
```
d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Error: The specified module could not be found.
d:\code\BitShares-JS\node_modules\bitcore\node_modules\bignum\build\Release\bignum.node
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at new require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\node_modules\bitcore\node_modules\bignum\index.js:4:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\node_modules\bitcore\util\util.js:2:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\node_modules\bitcore\util\index.js:1:80)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\node_modules\bitcore\lib\common\ECIES.js:2:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\node_modules\bitcore\lib\ECIES.js:3:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at d:\code\BitShares-JS\src\ecc\key_private.coffee:14:13
  at Object.<anonymous> (d:\code\BitShares-JS\src\ecc\key_private.coffee:120:5)
  at Object.<anonymous> (d:\code\BitShares-JS\src\ecc\key_private.coffee:2:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\src\ecc\index.coffee:2:17)
  at Object.<anonymous> (d:\code\BitShares-JS\src\ecc\index.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\code\BitShares-JS\test\CryptoFunctions.coffee:1:7)
  at Object.<anonymous> (d:\code\BitShares-JS\test\CryptoFunctions.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (d:\code\BitShares-JS\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at d:\code\BitShares-JS\node_modules\mocha\lib\mocha.js:184:27
  at Array.forEach (native)
  at Mocha.loadFiles (d:\code\BitShares-JS\node_modules\mocha\lib\mocha.js:181:14)
  at Mocha.run (d:\code\BitShares-JS\node_modules\mocha\lib\mocha.js:393:31)
  at Object.<anonymous> (d:\code\BitShares-JS\node_modules\mocha\bin\_mocha:380:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by jcalfee** [comment]
I use Ubuntu.  It looks like node is translating the paths ok on windows though.   I use nodejs-legacy from apt-get which installs v0.10.25 .. Also, lets make sure you're aware, this is not a full wallet; it is a library for wallets.

**Comment by cgafeng** [comment]
I know it's a library now, are there any plan to develop a wallet from this?
I kind of intersiting about such wallet, because the full wallet is awful because of the TITAN,
and the LW looks can't run on all platform(pc, web, ios, android) for now.

**Comment by jcalfee** [comment]
I'm developing this to work with the web_wallet ...

**Comment by cgafeng** [comment]
I think the mobile is very important

**Comment by jcalfee** [comment]
There are installable mobile wallets.  I expect that those will take most of the users on that platform.  I unit tests to pass on mobile platforms however and I have made some layout changes to help make it usable on those platforms.   I expect to have a mobile friendly web page for those to use temporarily or just casually but to use the installed wallet for a better platform experience.

**Comment by jcalfee** [comment]
I do not have windows to test with.  Maybe someone can suggest a fix.

**Comment by cgafeng** [comment]
use node-v0.10.33 on windows and finally let the "npm test" work.
After this work, i try to uninstall node-v0.10.33 and install node-v0.12.0, then failed again.
